Fix TypeError
TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.
This is caused by the width/height being undefined when
the effect is used upon mounting first...